### PR TITLE
Fix Issue #110 evaluateBoard function of tic-tac-toe example docs

### PR DESCRIPTION
**Pull request by zachtango**
Moved tie condition check to after win condition check in the evaluateBoard function of the tic-tac-toe example documentation

### CODE REVIEW

**Review by scottricity — APPROVED** [review]
I approve.

**Comment by sarahannali** [comment]
fixes #110

**Review by sarahannali — APPROVED** [review]

**Review by kevo1ution — CHANGES_REQUESTED** [review]
We should also make the related change in `examples/tictactoe` solution. (yes I know, not DRY, but couldn't figure out a way to template this in to the docs)

**Review by kevo1ution — APPROVED** [review]

**Comment by kevo1ution** [comment]
LGTM thanks!

**Pull request merged**
